name: plant_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.4.0
  page_transition: ^2.2.1
  mobile_scanner: ^6.0.10

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon/icon-new.png"
  adaptive_icon_background: "#296e48"
  adaptive_icon_foreground: "assets/launcher_icon/icon-new.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
